### ISSUE TITLE
I have issue with docker access

### ISSUE THREAD

**Issue by prakasa1904** [mhueter/docker-node-express-boilerplate#1]
do u know why this happen every request to expose port:
```
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Comment by prakasa1904** [comment]
my dockerfile name is `Development`.

content bellow:
```
FROM node:alpine

ENV NODE_VERSION 10.11.0

RUN mkdir -p /www/app/profile
RUN npm i -g yarn
RUN echo "127.0.0.1 localhost" >> /etc/hosts
RUN cat /etc/hosts
RUN hostname

WORKDIR /www/app/profile

COPY tools /www/app/profile
COPY package.json /www/app/profile
COPY yarn.lock /www/app/profile
COPY .env.example /www/app/profile/.env

RUN yarn cache clean && yarn install
```

**Comment by prakasa1904** [comment]
My dev compose file name is `dev.compose.yaml`.

The content bellow:

```
version: '3'
services:
  devetek-profile:
    networks:
      - deveteknetwork
    build:
      context: ./
      dockerfile: ./docker/Development
    volumes:
      - ./:/www/app/profile/
    ports:
      - 6501:6501
    depends_on:
      - redis
    environment:
      NODE_ENV: development
      DEVETEK_REDIS: devetek.redis.local
    command: ['yarn', 'start']
    container_name: devetek.profile.local

  nginx:
    image: nginx:1.14
    links:
      - devetek-profile
    ports:
      - '90:90'
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    networks:
      deveteknetwork:
        aliases:
          - redis.devetek.network
    image: redis:latest
    ports:
      - 6379:6381
    container_name: devetek.redis.local

networks:
  deveteknetwork:
    driver: bridge

```
